FROM oven/bun:1-alpine AS builder
ARG PUBLIC_AUTH_BACKEND
ARG PUBLIC_API_URL
ARG PUBLIC_APP_URL
ARG PUBLIC_IS_DEV_WORKER
ARG PUBLIC_AUTH0_CLIENT_ID
ARG PUBLIC_AUTH0_DOMAIN
ARG PUBLIC_AUTH0_AUDIENCE
ARG COOKIE_SECRET
ARG PUBLIC_SENTRY_DSN
ARG PUBLIC_SENTRY_ENVIRONMENT

COPY ./frontend/ /app/frontend/
COPY ./VERSION /app/
WORKDIR /app/frontend
RUN bun install --frozen-lockfile
WORKDIR /app/frontend/webapp
RUN bun install --frozen-lockfile
RUN cp vite.config.docker.ts vite.config.ts
RUN cp svelte.config.docker.js svelte.config.js
RUN cp src/instrumentation.server.docker.ts src/instrumentation.server.ts
RUN bun run build

FROM oven/bun:1-distroless AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/ /app/
EXPOSE 3000
CMD ["bun", "/app/frontend/webapp/build/index.js"]
