/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check if the API is running
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List articles
         * @description Get a paginated list of articles for the authenticated user
         */
        get: operations["listArticles"];
        put?: never;
        /**
         * Create article
         * @description Save a new article from a URL
         */
        post: operations["createArticle"];
        /**
         * Delete all articles
         * @description Delete all articles for the authenticated user
         */
        delete: operations["deleteAllArticles"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get article
         * @description Get a single article by ID
         */
        get: operations["getArticle"];
        put?: never;
        post?: never;
        /**
         * Delete article
         * @description Delete a single article by ID
         */
        delete: operations["deleteArticle"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Toggle favorite
         * @description Toggle the favorite status of an article
         */
        put: operations["toggleFavorite"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send article
         * @description Send an article to the user's Kindle device. Requires active subscription and non-bouncing email.
         */
        post: operations["sendArticle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Get the authenticated user's profile
         */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set device
         * @description Set or update the user's Kindle device email and auto-send preferences
         */
        put: operations["setDevice"];
        post?: never;
        /**
         * Delete device
         * @description Remove the user's Kindle device email
         */
        delete: operations["deleteDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange auth code
         * @description Exchange an OAuth authorization code for access tokens (Auth0 only)
         */
        post: operations["authTokenExchange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/mailjet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mailjet webhook
         * @description Receive bounce notifications from Mailjet (Mailjet only)
         */
        post: operations["mailjetWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Article: {
            /** @description User account ID */
            account: string;
            /** @description Article ID */
            id: string;
            /** @description Article URL */
            url: string;
            /**
             * Format: date-time
             * @description Article creation timestamp
             */
            createdAt: string;
            /** @description Article title */
            title?: string;
            /** @description Article content */
            content?: string;
            /** @description Article author */
            author?: string;
            /** @description Site name */
            siteName?: string;
            /** @description Source domain */
            sourceDomain?: string;
            /** @description Article excerpt */
            excerpt?: string;
            /** @description Image URL */
            imageUrl?: string;
            /** @description Content type */
            contentType?: string;
            /** @description Article language */
            language?: string;
            /** @description Error message if processing failed */
            error?: string;
            /** @description Word count */
            wordCount?: number;
            /** @description Estimated reading time in minutes */
            readingTimeMinutes?: number;
            /**
             * Format: date-time
             * @description Original publication date
             */
            publishedAt?: string;
            /** @description Whether article is favorited */
            favorite?: boolean;
        };
        ArticleRequest: {
            /** @description URL of the article to save */
            url: string;
        };
        ArticleResponse: {
            /** @description Article ID */
            id: string;
            /** @description Article title */
            title: string;
            /** @description Article URL */
            url: string;
        };
        ListArticlesResponse: {
            /** @description List of articles */
            articles: components["schemas"]["Article"][];
            /** @description Current page number */
            page: number;
            /** @description Number of articles per page */
            page_size: number;
            /** @description Total number of articles */
            total: number;
            /** @description Whether there are more pages */
            has_more: boolean;
        };
        DeleteArticleResponse: {
            /** @description Number of articles deleted */
            deleted: number;
        };
        FavoriteResponse: {
            /** @description New favorite status */
            favorite: boolean;
        };
        SendArticleResponse: {
            /** @description Send status */
            status: string;
        };
        SendArticleResponseWithCount: {
            /** @description Send status */
            status: string;
            /** @description Total sends count */
            sends_count: number;
        };
        UserProfile: {
            /** @description User account ID */
            account: string;
            /** @description User email address */
            email: string;
            /** @description Kindle device email */
            device_email: string;
            /** @description Whether to auto-send articles */
            auto_send: boolean;
        };
        BounceInfo: {
            /**
             * Format: date-time
             * @description Bounce timestamp
             */
            timestamp: string;
            /** @description Bounce error message */
            error: string;
        };
        DeviceRequest: {
            /** @description Kindle device email address */
            device_email: string;
            /** @description Whether to auto-send articles to device */
            auto_send: boolean;
        };
        DeviceResponse: {
            /** @description Kindle device email address */
            device_email: string;
            /** @description Whether to auto-send articles */
            auto_send: boolean;
        };
        AuthTokenExchangeRequest: {
            /** @description Authorization code from OAuth provider */
            code: string;
            /** @description Redirect URI used in authorization request */
            redirect_uri: string;
            /**
             * @description OAuth grant type
             * @default authorization_code
             */
            grant_type: string;
        };
        AuthTokenExchangeResponse: {
            /** @description OAuth access token */
            access_token: string;
            /** @description OAuth refresh token */
            refresh_token?: string;
            /** @description JWT ID token */
            id_token?: string;
            /** @description User email extracted from ID token */
            email?: string;
            /** @description Token type (typically "Bearer") */
            token_type: string;
            /** @description Token expiration time in seconds */
            expires_in: number;
        };
        ErrorResponse: {
            /** @description Error message */
            error: string;
        };
        HealthResponse: {
            /** @description Health status */
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listArticles: {
        parameters: {
            query?: {
                /** @description Page number, default is 1 */
                page?: number;
                /** @description Number of articles per page, default is 20, max is 100 */
                page_size?: number;
                /** @description Filter by favorite status */
                favorite?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of articles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListArticlesResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createArticle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticleRequest"];
            };
        };
        responses: {
            /** @description Article created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArticleResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteAllArticles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Articles deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteArticleResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Article"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Article not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteArticleResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    toggleFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Favorite status toggled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FavoriteResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sendArticle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Article ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Article sent successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Article not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    setDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceRequest"];
            };
        };
        responses: {
            /** @description Device settings updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    authTokenExchange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthTokenExchangeRequest"];
            };
        };
        responses: {
            /** @description Token exchange successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenExchangeResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Token exchange failed */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    mailjetWebhook: {
        parameters: {
            query: {
                /** @description Webhook secret for verification */
                secret: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Event type (e.g., "bounce") */
                    event?: string;
                    /** @description Email address */
                    email?: string;
                    /**
                     * Format: int64
                     * @description Event timestamp
                     */
                    time?: number;
                    /** @description Error message */
                    error?: string;
                    /** @description Additional comments */
                    comment?: string;
                }[];
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        status?: string;
                    };
                };
            };
        };
    };
}
