name: Deploy Lambda - Production

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - cmd/lambda/**
      - go.mod
      - go.sum
      - infra/**
      - internal/**
      - VERSION

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      bucket: ${{ vars.SAVETOINK_BUCKET }}
      aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
      aws_region: ${{ vars.AWS_REGION }}
