name: Deploy Lambda - Prod

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - backend/**
      - go.mod
      - go.sum
      - infra/**
      - VERSION

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/test-backend.yml

  deploy:
    uses: ./.github/workflows/deploy-lambda.yml
    needs: tests
    with:
      bucket: ${{ vars.SAVETOINK_BUCKET }}
      aws_role_arn: ${{ vars.AWS_ROLE_ARN }}
      aws_region: ${{ vars.AWS_REGION }}
