name: Deploy Lambda - Dev

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - backend/**
      - go.mod
      - go.sum
      - infra/**
      - VERSION

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      bucket: ${{ vars.SAVETOINK_BUCKET_DEV }}
      aws_role_arn: ${{ vars.AWS_ROLE_ARN_DEV }}
      aws_region: ${{ vars.AWS_REGION_DEV }}
