name: Build and publish Docker http image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - VERSION

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      app: http
      dockerfile: backend/Dockerfile
      build-args: |
        APP=http
