name: Build and publish Docker http image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - VERSION

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      app: http
