name: Build and publish Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - VERSION

permissions:
  id-token: write
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Set up Just
        uses: extractions/setup-just@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push CLI Docker image
        run: just build-cli-docker push-cli-docker

      - name: Build and push API Docker image
        run: just build-http-docker push-http-docker
