name: Build and publish Docker webapp image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - VERSION

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      app: webapp
      dockerfile: frontend/Dockerfile
      build-args: |
        APP=webapp
        PUBLIC_AUTH_BACKEND=sharedKey
        PUBLIC_IS_DEV_WORKER=false
