name: Build and publish Docker CLI image

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - VERSION

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      app: cli
      dockerfile: backend/Dockerfile
      build-args: |
        APP=cli
