name: Opencode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write

jobs:
  opencode:
    if: |
      contains(github.event.comment.body, '/opencode')

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Configure Git user
        run: |
          git config --global user.name "Opencode[bot]"
          git config --global user.email "shaftoe@users.noreply.github.com"

      - name: Run OpenCode
        uses: anomalyco/opencode/github@latest
        env:
          ZHIPU_API_KEY: ${{ secrets.ZAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          model: zai-coding-plan/glm-4.7
          use_github_token: true
