name: Deploy Webapp on Cloudflare

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
    secrets:
      COOKIE_SECRET:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true
      CLOUDFLARE_API_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment: ${{ inputs.environment }}
    steps:
      - uses: ./.github/actions/checkout
      - uses: oven-sh/setup-bun@v2

      - name: Build webapp
        run: cd frontend/webapp && bun install && bun run build
        env:
          PUBLIC_AUTH_BACKEND: ${{ vars.PUBLIC_AUTH_BACKEND }}
          PUBLIC_IS_DEV_WORKER: ${{ vars.PUBLIC_IS_DEV_WORKER }}
          PUBLIC_SENTRY_DSN: ${{ vars.PUBLIC_SENTRY_DSN }}
          PUBLIC_SENTRY_ENVIRONMENT: ${{ vars.PUBLIC_SENTRY_ENVIRONMENT }}

      - name: Upload secrets
        working-directory: frontend/webapp
        run: |
          echo '{
            "COOKIE_SECRET": "${{ secrets.COOKIE_SECRET }}",
            "SENTRY_AUTH_TOKEN": "${{ secrets.SENTRY_AUTH_TOKEN }}",
            "PUBLIC_API_URL": "${{ vars.PUBLIC_API_URL }}",
            "PUBLIC_APP_URL": "${{ vars.PUBLIC_APP_URL }}",
            "PUBLIC_AUTH0_AUDIENCE": "${{ vars.PUBLIC_AUTH0_AUDIENCE }}",
            "PUBLIC_AUTH0_CLIENT_ID": "${{ vars.PUBLIC_AUTH0_CLIENT_ID }}",
            "PUBLIC_AUTH0_DOMAIN": "${{ vars.PUBLIC_AUTH0_DOMAIN }}",
            "PUBLIC_IS_DEV_WORKER": "${{ vars.PUBLIC_IS_DEV_WORKER }}",
            "PUBLIC_SENTRY_ENVIRONMENT": "${{ vars.PUBLIC_SENTRY_ENVIRONMENT }}"
          }' | bunx wrangler secret bulk --env "$CLOUDFLARE_ENV"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_ENV: ${{ inputs.environment }}

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: ${{ inputs.environment }}
          packageManager: bun
          workingDirectory: frontend/webapp
          wranglerVersion: "4.75.0"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
